# -*- coding: utf-8 -*-
"""CNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iC_qimhN_fSEBXroqPaf4ToPkWVppHAa
"""

# This script trains and evaluates machine learning models to classify brain MRI images as glioma, meningioma, notumor, or pituitary. It includes data loading, preprocessing, model training, and performance evaluation on a separate test set.

# Import os for working with file paths and folder contents
import os

# Import numpy for numerical operations used later in the analysis
import numpy as np

# Import matplotlib to display sample MRI images and plots
import matplotlib.pyplot as plt

# Import PIL so image files can be opened and displayed
from PIL import Image

# Define the folder paths for the training and testing image datasets
train_dir = "Training"
test_dir = "Testing"

# Define the four diagnosis classes used throughout the project
classes = ["glioma", "meningioma", "notumor", "pituitary"]

# Loop through the training and testing folders to verify that each class subfolder exists
for folder in [train_dir, test_dir]:
    print(f"\n{folder}")
    for c in classes:
        path = os.path.join(folder, c)
        print(c, "exists" if os.path.exists(path) else "missing")

# Loop through the training and testing folders and count how many image files appear in each diagnosis category to confirm the dataset size and class balance
for folder in [train_dir, test_dir]:
    print(f"\n{folder} image counts:")
    for c in classes:
        path = os.path.join(folder, c)
        count = len([f for f in os.listdir(path) if f.lower().endswith((".jpg", ".jpeg", ".png"))])
        print(f"{c}: {count}")

# Create a 1x4 plot to display one sample image from each diagnosis category
fig, axes = plt.subplots(1, 4, figsize=(16, 4))

# Loop through each class, open one example image, and display it
for i, c in enumerate(classes):
    class_path = os.path.join(train_dir, c)
    img_name = os.listdir(class_path)[0]
    img_path = os.path.join(class_path, img_name)

    img = Image.open(img_path)
    axes[i].imshow(img, cmap="gray")
    axes[i].set_title(c)
    axes[i].axis("off")

# Adjust spacing and show the final figure
plt.tight_layout()
plt.show()

# Import TensorFlow and Keras tools used to preprocess images and build the neural network models
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout

# Import evaluation metrics used to summarize classification performance
from sklearn.metrics import classification_report, confusion_matrix

# Import EarlyStopping so training can stop once validation performance no longer improves
from tensorflow.keras.callbacks import EarlyStopping

# Set the image dimensions and batch size that will be used when loading images for the model
img_height = 224
img_width = 224
batch_size = 32

# Create an image generator for the training data that applies MobileNetV2 preprocessing, reserves 20% of the training images for validation, and adds augmentation to improve generalization
train_datagen = ImageDataGenerator(
    preprocessing_function=tf.keras.applications.mobilenet_v2.preprocess_input,
    validation_split=0.2,
    rotation_range=15,
    zoom_range=0.1,
    width_shift_range=0.1,
    height_shift_range=0.1,
    horizontal_flip=True
)

# Create a separate image generator for the test data that only applies preprocessing because test images should not be augmented
test_datagen = ImageDataGenerator(
    preprocessing_function=tf.keras.applications.mobilenet_v2.preprocess_input
)

# Load images from the training folder, resize them to the chosen input size, and use 80% of the folder for model training
train_generator = train_datagen.flow_from_directory(
    train_dir,
    target_size=(img_height, img_width),
    color_mode="rgb",
    batch_size=batch_size,
    class_mode="categorical",
    subset="training",
    shuffle=True
)

# Load the remaining 20% of the training folder as a validation set to monitor model performance on unseen images during training
val_generator = train_datagen.flow_from_directory(
    train_dir,
    target_size=(img_height, img_width),
    color_mode="rgb",
    batch_size=batch_size,
    class_mode="categorical",
    subset="validation",
    shuffle=True
)

# Load images from the separate testing folder for final model evaluation. Shuffle is turned off so predictions stay aligned with the true labels
test_generator = test_datagen.flow_from_directory(
    test_dir,
    target_size=(img_height, img_width),
    color_mode="rgb",
    batch_size=batch_size,
    class_mode="categorical",
    shuffle=False
)

# Print the numeric label assigned to each diagnosis class by the image generator
# This mapping is used later when interpreting predictions and the confusion matrix
print(train_generator.class_indices)

# Import the Keras functions needed to build a transfer learning model with MobileNetV2
from tensorflow.keras import Input, Model
from tensorflow.keras.layers import Dense, Dropout, GlobalAveragePooling2D
from tensorflow.keras.applications import MobileNetV2

# Load the pretrained MobileNetV2 model without its original output layer so it can be used as a feature extractor for the MRI images
base_model = MobileNetV2(
    weights="imagenet",
    include_top=False,
    input_shape=(img_height, img_width, 3)
)

# Freeze the pretrained layers so only the new classification layers are trained at first
base_model.trainable = False

# Build a new model by passing the MRI images through MobileNetV2, then adding pooling, dropout, and a four-class softmax output layer
inputs = Input(shape=(img_height, img_width, 3))
x = base_model(inputs, training=False)
x = GlobalAveragePooling2D()(x)
x = Dropout(0.3)(x)
outputs = Dense(4, activation="softmax")(x)

# Create the final transfer learning model
model = Model(inputs, outputs)

# Compile the transfer learning model by specifying the optimizer, loss function, and accuracy metric used during training
model.compile(
    optimizer="adam",
    loss="categorical_crossentropy",
    metrics=["accuracy"]
)

# Print a summary of the model architecture to confirm its layers and parameters
model.summary()

# Create an early stopping rule that monitors validation loss and ends training if performance does not improve for 3 consecutive epochs
early_stop = EarlyStopping(
    monitor="val_loss",
    patience=3,
    restore_best_weights=True
)

# Train the model on the training images, evaluate it on the validation set after each epoch, and apply early stopping to reduce overfitting
history = model.fit(
    train_generator,
    validation_data=val_generator,
    epochs=15,
    callbacks=[early_stop]
)

# Plot training and validation accuracy across epochs to show how model performance changed during training
plt.figure(figsize=(8, 5))
plt.plot(history.history["accuracy"], label="Training Accuracy")
plt.plot(history.history["val_accuracy"], label="Validation Accuracy")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.title("Training and Validation Accuracy")
plt.legend()
plt.show()

# Plot training and validation loss across epochs to show how model error changed during training
plt.figure(figsize=(8, 5))
plt.plot(history.history["loss"], label="Training Loss")
plt.plot(history.history["val_loss"], label="Validation Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Training and Validation Loss")
plt.legend()
plt.show()

# Evaluate the final model on the separate test image set and print the resulting loss and accuracy values
test_loss, test_acc = model.evaluate(test_generator)
print("Test Loss:", test_loss)
print("Test Accuracy:", test_acc)

# Generate predicted probabilities for each test image, then convert them into final class predictions
y_pred_probs = model.predict(test_generator)
y_pred = np.argmax(y_pred_probs, axis=1)

# Store the true class labels from the test set for comparison
y_true = test_generator.classes

# Save the class names in the same order used by the test generator
class_names = list(test_generator.class_indices.keys())
print(class_names)

# Print a classification report showing precision, recall, F1-score, and support for each diagnosis class in the test set
print(classification_report(y_true, y_pred, target_names=class_names))

# Create a confusion matrix to compare the true and predicted classes for the test images
cm = confusion_matrix(y_true, y_pred)

# Display the confusion matrix as a heatmap-style plot
plt.figure(figsize=(7, 5))
plt.imshow(cm, interpolation="nearest")
plt.title("Confusion Matrix")
plt.colorbar()

# Label the x-axis and y-axis with the diagnosis class names
tick_marks = np.arange(len(class_names))
plt.xticks(tick_marks, class_names, rotation=45)
plt.yticks(tick_marks, class_names)

# Add the raw count values inside each cell of the confusion matrix
for i in range(cm.shape[0]):
    for j in range(cm.shape[1]):
        plt.text(j, i, cm[i, j], ha="center", va="center")

# Add axis labels and display the final plot
plt.ylabel("True Label")
plt.xlabel("Predicted Label")
plt.tight_layout()
plt.show()